# Generated by Django 5.1.4 on 2024-12-24 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_bill', '0003_alter_expense_paid_by_alter_expense_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemshare',
            name='share_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
