# Generated by Django 5.1.4 on 2024-12-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_bill', '0005_alter_itemshare_item_alter_itemshare_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemshare',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='split_bill.item'),
        ),
        migrations.AlterField(
            model_name='itemshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
